### PR TITLE
Minor improvements && bug fixes

### PR DESCRIPTION
**Pull request by DaazKu**
Some minor improvements and bug fixes.

The most important points are 
- 764d0d7 Without this change users having the plugin already installed will run into trouble.
- 143b58f Long story short I encountered a problem with that while creating a new plugin dependant on this one

### CODE REVIEW

**Comment by DaazKu** [comment]
Good feedback!
I'm gonna wait on your reply about the fix.

**Comment by R-J** [comment]
I'm only writing plugins out of fun. So my goal is to make them look cool and elegant. I think having that fix in structure would be cleaner, though surely not foolproof.

But you are the one that is going to use it in critical environments. So please decide which place you think is better suited for your needs and I'll merge the PR

**Comment by DaazKu** [comment]
I like cleaner. This should work :)

**Comment by R-J** [comment]
Many thanks!

**Comment by DaazKu** [comment]
No problem :D. Merge whenever!

**Pull request merged**
